=== foxrider1998/QA-fazztrack/schema/schema.json
{
    "$schema": "https://json-schema.org/draft/2019-09/schema",
    "$id": "http://example.com/example.json",
    "type": "object",
    "default": {},
    "title": "Root Schema",
    "required": [
        "id",
        "firstName",
        "lastName",
        "age",
        "occupation",
        "nationality",
        "hobbies",
        "gender",
        "createdDate",
        "updatedDate"
    ],
    "properties": {
        "id": {
            "type": "null",
            "default": null,
            "title": "The id Schema",
            "examples": [
                null
            ]
        },
        "firstName": {
            "type": "string",
            "default": "",
            "title": "The firstName Schema",
            "examples": [
                "Hendri"
            ]
        },
        "lastName": {
            "type": "string",
            "default": "",
            "title": "The lastName Schema",
            "examples": [
                "Antomy"
            ]
        },
        "age": {
            "type": "integer",
            "default": 0,
            "title": "The age Schema",
            "examples": [
                30
            ]
        },
        "occupation": {
            "type": "string",
            "default": "",
            "title": "The occupation Schema",
            "examples": [
                "QA Engineer"
            ]
        },
        "nationality": {
            "type": "string",
            "default": "",
            "title": "The nationality Schema",
            "examples": [
                "Indonesia"
            ]
        },
        "hobbies": {
            "type": "array",
            "default": [],
            "title": "The hobbies Schema",
            "items": {
                "type": "string",
                "default": "",
                "title": "A Schema",
                "examples": [
                    "Gaming"
                ]
            },
            "examples": [
                [
                    "Gaming"]
            ]
        },
        "gender": {
            "type": "string",
            "default": "",
            "title": "The gender Schema",
            "examples": [
                "MALE"
            ]
        },
        "createdDate": {
            "type": "string",
            "default": "",
            "title": "The createdDate Schema",
            "examples": [
                "2022-11-27T02:36:45.676Z"
            ]
        },
        "updatedDate": {
            "type": "string",
            "default": "",
            "title": "The updatedDate Schema",
            "examples": [
                "2022-11-27T02:36:45.676Z"
            ]
        }
    },
    "examples": [{
        "id": null,
        "firstName": "Hendri",
        "lastName": "Antomy",
        "age": 30,
        "occupation": "QA Engineer",
        "nationality": "Indonesia",
        "hobbies": [
            "Gaming"
        ],
        "gender": "MALE",
        "createdDate": "2022-11-27T02:36:45.676Z",
        "updatedDate": "2022-11-27T02:36:45.676Z"
    }]
}

=== foxrider1998/QA-fazztrack/dataJson/dataJson.json
{
    "id": "1",
    "firstName": "Aris",
    "lastName": "Saputra",
    "age": 24,
    "occupation": "karyawan",
    "nationality": "Indonesia",
    "hobbies": [
        "Manga", "Sales", "Selling", "tawuran"
    ],
    "gender": "MALE",
    "createdDate": "2022-11-26T03:04:09.638Z",
    "updatedDate": "2022-11-26T03:04:09.638Z"
}
